# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_parsers:
    strategy:
      matrix:
        language: [csharp]
          
        #[csharp, java, javascript, python, ruby, php]

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Kaitai
        run: |
          curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.10/kaitai-struct-compiler_0.10_all.deb
          sudo apt-get install ./kaitai-struct-compiler_0.10_all.deb
          
      - name: Compile definitions
        run: kaitai-struct-compiler -t ${{ matrix.language }} --outdir build $GITHUB_WORKSPACE/definitions/aoe2record.ksy

      - name: Store Compiled Parser
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}
          if-no-files-found: ignore
          path: |
            build
  
  compile_csharp:
    runs-on: ubuntu-latest
    needs: [compile_parsers]

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - uses: actions/download-artifact@v4      
          with:
            name: csharp
            path: $GITHUB_WORKSPACE/platform/csharp
        
        - uses: actions/cache@v3
          with:
            path: ~/.nuget/packages
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            restore-keys: |
                ${{ runner.os }}-nuget
        - name: Restore dependencies
          run: dotnet restore $GITHUB_WORKSPACE/platform/csharp
        - name: Build
          run: dotnet build --configuration Release --no-restore $GITHUB_WORKSPACE/platform/csharp
        - name: Pack
          run: dotnet pack --configuration Release --no-restore $GITHUB_WORKSPACE/platform/csharp
        - name: Store lib
          uses: actions/upload-artifact@v4
          with:
            name: lib-csharp
            if-no-files-found: ignore
            path: |
                platform/csharp/bin/Release/net8.0/
        - name: Publish nuget
          run: dotnet nuget push "platform/csharp/bin/Release/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
        
        

